name: "Release"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Post release to Discord
        uses: SethCohen/github-releases-to-discord@v1.15.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "16753920"
          username: "kilobyte-bot"
          avatar_url: "https://avatars.githubusercontent.com/u/98578253?s=200&v=4"
          content: "@here A new release has been published! :rocket:"
          footer_title: ${{ github.event.release.name }}
          footer_timestamp: true
